version: "3.8"

services:
  typesense:
    image: typesense/typesense:27.1
    container_name: typesense_server
    restart: always
    ports:
      - "8108:8108"
    volumes:
      - ~/typesense_data:/data
    command: >
      --data-dir /data
      --api-key=opannapoTESTapiKEY123
      --enable-cors
